#djpeg -grayscale -outfile test0.pgm app0.jpg
#djpeg -grayscale -outfile test10.pgm app10.jpg
#djpeg -grayscale -outfile test20.pgm app20.jpg
#djpeg -grayscale -outfile test30.pgm app30.jpg
#djpeg -grayscale -outfile test40.pgm app40.jpg
#djpeg -grayscale -outfile test50.pgm app50.jpg
#djpeg -grayscale -outfile test60.pgm app60.jpg
#djpeg -grayscale -outfile test70.pgm app70.jpg
#djpeg -grayscale -outfile test80.pgm app80.jpg
#djpeg -grayscale -outfile test90.pgm app90.jpg
#djpeg -grayscale -outfile test100.pgm app100.jpg
#djpeg -grayscale -outfile panda90.pgm  panda90.jpg
#djpeg -grayscale -outfile panda91.pgm  panda91.jpg
#djpeg -grayscale -outfile panda92.pgm  panda92.jpg
#djpeg -grayscale -outfile panda93.pgm  panda93.jpg
#djpeg -grayscale -outfile panda94.pgm  panda94.jpg
#djpeg -grayscale -outfile panda95.pgm  panda95.jpg
#djpeg -grayscale -outfile panda96.pgm  panda96.jpg
#djpeg -grayscale -outfile panda97.pgm  panda97.jpg
#djpeg -grayscale -outfile panda98.pgm  panda98.jpg
#djpeg -grayscale -outfile panda99.pgm  panda99.jpg
djpeg -grayscale -outfile panda4x100.pgm panda4x100.jpg
djpeg -grayscale -outfile panda4x90.pgm  panda4x90.jpg
djpeg -grayscale -outfile panda4x80.pgm  panda4x80.jpg
djpeg -grayscale -outfile panda4x70.pgm  panda4x70.jpg
djpeg -grayscale -outfile panda4x60.pgm  panda4x60.jpg
djpeg -grayscale -outfile panda4x50.pgm  panda4x50.jpg
djpeg -grayscale -outfile panda4x40.pgm  panda4x40.jpg
djpeg -grayscale -outfile panda4x30.pgm  panda4x30.jpg
djpeg -grayscale -outfile panda4x20.pgm  panda4x20.jpg
djpeg -grayscale -outfile panda4x10.pgm  panda4x10.jpg
djpeg -grayscale -outfile panda4x0.pgm   panda4x0.jpg
