#cjpeg -quality 0 -grayscale -outfile app0.jpg test1.pgm
#cjpeg -quality 10 -grayscale -outfile app10.jpg test1.pgm
#cjpeg -quality 20 -grayscale -outfile app20.jpg test1.pgm
#cjpeg -quality 30 -grayscale -outfile app30.jpg test1.pgm
#cjpeg -quality 40 -grayscale -outfile app40.jpg test1.pgm
#cjpeg -quality 50 -grayscale -outfile app50.jpg test1.pgm
#cjpeg -quality 60 -grayscale -outfile app60.jpg test1.pgm
#cjpeg -quality 70 -grayscale -outfile app70.jpg test1.pgm
#cjpeg -quality 80 -grayscale -outfile app80.jpg test1.pgm
#cjpeg -quality 90 -grayscale -outfile app90.jpg test1.pgm
#cjpeg -quality 100 -grayscale -outfile app100.jpg test1.pgm
#cjpeg -quality 0 -grayscale -outfile     app0.jpg test1_32_18.pgm
#cjpeg -quality 10 -grayscale -outfile   app10.jpg test1_32_18.pgm
#cjpeg -quality 20 -grayscale -outfile   app20.jpg test1_32_18.pgm
#cjpeg -quality 30 -grayscale -outfile   app30.jpg test1_32_18.pgm
#cjpeg -quality 40 -grayscale -outfile   app40.jpg test1_32_18.pgm
#cjpeg -quality 50 -grayscale -outfile   app50.jpg test1_32_18.pgm
#cjpeg -quality 60 -grayscale -outfile   app60.jpg test1_32_18.pgm
#cjpeg -quality 70 -grayscale -outfile   app70.jpg test1_32_18.pgm
#cjpeg -quality 80 -grayscale -outfile   app80.jpg test1_32_18.pgm
#cjpeg -quality 90 -grayscale -outfile   app90.jpg test1_32_18.pgm
#cjpeg -quality 100 -grayscale -outfile app100.jpg test1_32_18.pgm
#cjpeg -quality 0 -grayscale -outfile     app0.jpg input.pgm
#cjpeg -quality 10 -grayscale -outfile   app10.jpg input.pgm
#cjpeg -quality 20 -grayscale -outfile   app20.jpg input.pgm
#cjpeg -quality 30 -grayscale -outfile   app30.jpg input.pgm
#cjpeg -quality 40 -grayscale -outfile   app40.jpg input.pgm
#cjpeg -quality 50 -grayscale -outfile   app50.jpg input.pgm
#cjpeg -quality 60 -grayscale -outfile   app60.jpg input.pgm
#cjpeg -quality 70 -grayscale -outfile   app70.jpg input.pgm
#cjpeg -quality 80 -grayscale -outfile   app80.jpg input.pgm
#cjpeg -quality 90 -grayscale -outfile   app90.jpg input.pgm
#cjpeg -quality 100 -grayscale -outfile app100.jpg knn.pgm
#cjpeg -quality 91 -grayscale -outfile   app91.jpg input.pgm
#cjpeg -quality 92 -grayscale -outfile   app92.jpg input.pgm
#cjpeg -quality 93 -grayscale -outfile   app93.jpg input.pgm
#cjpeg -quality 94 -grayscale -outfile   app94.jpg input.pgm
#cjpeg -quality 95 -grayscale -outfile   app95.jpg input.pgm
#cjpeg -quality 96 -grayscale -outfile   app96.jpg input.pgm
#cjpeg -quality 97 -grayscale -outfile   app97.jpg input.pgm
#cjpeg -quality 98 -grayscale -outfile   app98.jpg input.pgm
#cjpeg -quality 99 -grayscale -outfile   app99.jpg input.pgm
#cjpeg -quality 100 -grayscale -outfile app100.jpg input.pgm
#cjpeg -quality 90 -grayscale -outfile   panda90.jpg  panda.pgm
#cjpeg -quality 91 -grayscale -outfile   panda91.jpg  panda.pgm
#cjpeg -quality 92 -grayscale -outfile   panda92.jpg  panda.pgm
#cjpeg -quality 93 -grayscale -outfile   panda93.jpg  panda.pgm
#cjpeg -quality 94 -grayscale -outfile   panda94.jpg  panda.pgm
#cjpeg -quality 95 -grayscale -outfile   panda95.jpg  panda.pgm
#cjpeg -quality 96 -grayscale -outfile   panda96.jpg  panda.pgm
#cjpeg -quality 97 -grayscale -outfile   panda97.jpg  panda.pgm
#cjpeg -quality 98 -grayscale -outfile   panda98.jpg  panda.pgm
#cjpeg -quality 99 -grayscale -outfile   panda99.jpg  panda.pgm
cjpeg -quality 100 -grayscale -outfile  panda4x100.jpg panda4x.pgm
cjpeg -quality 90 -grayscale -outfile   panda4x90.jpg  panda4x.pgm
cjpeg -quality 80 -grayscale -outfile   panda4x80.jpg  panda4x.pgm
cjpeg -quality 70 -grayscale -outfile   panda4x70.jpg  panda4x.pgm
cjpeg -quality 60 -grayscale -outfile   panda4x60.jpg  panda4x.pgm
cjpeg -quality 50 -grayscale -outfile   panda4x50.jpg  panda4x.pgm
cjpeg -quality 40 -grayscale -outfile   panda4x40.jpg  panda4x.pgm
cjpeg -quality 30 -grayscale -outfile   panda4x30.jpg  panda4x.pgm
cjpeg -quality 20 -grayscale -outfile   panda4x20.jpg  panda4x.pgm
cjpeg -quality 10 -grayscale -outfile   panda4x10.jpg  panda4x.pgm
cjpeg -quality 0 -grayscale -outfile    panda4x0.jpg   panda4x.pgm
